var path          = require('path');
var request       = require('request');


function IndexController() {

  /**
   * Render the index.html file generated by webpack
   */
  this.renderIndexFile = function(req, res) {
    return res.render(path.join(__dirname, '../../dist', 'index.html'));
  };

  /**
   * Sample data request
   */
  this.getSunrise = function(req, res) {
    var latitude = req.params.latitude;
    var longitude = req.params.longitude;
    var options = {
      uri: `https://api.sunrise-sunset.org/json?lat=${latitude}&lng=${longitude}`,
      method: 'GET',
    };
    
    request(options, function(err, httpResponse, body) {
      try {
        body = JSON.parse(body);
        res.json(body);
      } catch (e) {
        res.json(['not found']);
      }
    });
  };
}

const indexController = new IndexController();
module.exports = indexController;
